const app=document.getElementById('app'),cards=document.getElementById('cards'),create=document.getElementById('create'),error=document.getElementById('error');let chars=[];
const nui=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json()).catch(()=>({}));
const money=n=>'$'+Number(n||0).toLocaleString('en-US');
function render(list){chars=list||[];cards.innerHTML='';chars.forEach(c=>{const el=document.createElement('article');el.className='card '+(c.empty?'empty':'');if(c.empty){el.innerHTML=`<div><div style="font-size:28px;margin-bottom:12px">＋</div><div>EMPTY SLOT</div><div style="font-size:10px;margin-top:8px">Create a new life</div></div>`;el.onclick=()=>openCreate(c.slot)}else{el.innerHTML=`<div class="slot">SLOT ${String(c.slot).padStart(2,'0')}</div><div class="name">${esc(c.firstname)} ${esc(c.lastname)}</div><div class="cid">${esc(c.citizenid)}</div><div class="meta"><span class="pill">${esc(c.job)}${c.jobGrade?' · '+esc(c.jobGrade):''}</span><span class="pill">${esc(c.birthdate)}</span><span class="pill">${esc(c.gender)}</span></div><div class="play">SELECT →</div>`;el.onclick=()=>select(c.slot)}cards.appendChild(el)})}
function select(slot){nui('select',{slot});document.querySelectorAll('.card').forEach((x,i)=>x.classList.toggle('active',i===slot-1));}
function openCreate(slot){cards.classList.add('hidden');document.querySelector('.intro').classList.add('hidden');create.classList.remove('hidden');create.dataset.slot=slot;error.textContent=''}
document.getElementById('back').onclick=()=>{create.classList.add('hidden');cards.classList.remove('hidden');document.querySelector('.intro').classList.remove('hidden')};
document.getElementById('createBtn').onclick=async()=>{error.textContent='';const data={slot:Number(create.dataset.slot),firstname:v('firstname'),lastname:v('lastname'),nationality:v('nationality'),birthdate:v('birthdate'),gender:v('gender')};if(!data.firstname||!data.lastname||!data.nationality||!data.birthdate){error.textContent='Please complete every field.';return}const r=await nui('create',data);if(!r.ok)error.textContent=r.error||'Unable to create character.'};
function v(id){return document.getElementById(id).value.trim()}function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
window.addEventListener('message',e=>{const d=e.data||{};if(d.action==='open'){app.classList.remove('hidden')}if(d.action==='characters'){render(d.characters)}if(d.action==='transition'){document.querySelector('.sub').textContent=d.text||'Loading...'}if(d.action==='hide'){app.classList.add('hidden')}});
// Double-click a populated card to play; single click previews the character.
cards.addEventListener('dblclick',e=>{const card=e.target.closest('.card');if(!card||card.classList.contains('empty'))return;const slot=[...cards.children].indexOf(card)+1;nui('play',{slot})});
