const app=document.getElementById('app'),cards=document.getElementById('cards'),create=document.getElementById('create'),error=document.getElementById('error');let chars=[];
const nui=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json()).catch(e=>{console.error(`[BotRP] NUI ${name} failed`,e);return {ok:false,error:'Connection to the game client failed.'}});
function render(list){chars=list||[];const count=document.getElementById('slotCount');if(count)count.textContent=String(chars.filter(c=>!c.empty).length).padStart(2,'0');cards.innerHTML='';chars.forEach(c=>{const el=document.createElement('article');el.className='card '+(c.empty?'empty':'');if(c.empty){el.innerHTML=`<div><div class="plus">＋</div><strong>EMPTY SLOT</strong><small>Create a new life</small></div>`;el.onclick=()=>openCreate(c.slot)}else{el.innerHTML=`<div class="slot">SLOT ${String(c.slot).padStart(2,'0')}</div><div class="name">${esc(c.firstname)} ${esc(c.lastname)}</div><div class="cid">${esc(c.citizenid)}</div><div class="meta"><span class="pill">${esc(c.job)}${c.jobGrade?' · '+esc(c.jobGrade):''}</span><span class="pill">${esc(c.birthdate)}</span><span class="pill">${esc(c.gender)}</span></div><button type="button" class="play">PLAY CHARACTER <span>→</span></button>`;el.onclick=()=>select(c.slot);const btn=el.querySelector('.play');btn.onclick=async e=>{e.preventDefault();e.stopPropagation();btn.disabled=true;btn.textContent='ENTERING LOS SANTOS…';const r=await nui('play',{slot:c.slot});if(!r.ok){btn.disabled=false;btn.innerHTML='PLAY CHARACTER <span>→</span>';if(error)error.textContent=r.error||'Unable to load character.'}}}cards.appendChild(el)})}
function select(slot){nui('select',{slot});document.querySelectorAll('.card').forEach(x=>x.classList.remove('selected'));const el=chars[slot-1];if(el&&!el.empty)document.querySelectorAll('.card')[slot-1]?.classList.add('selected');}
function openCreate(slot){cards.classList.add('hidden');document.querySelector('.intro')?.classList.add('hidden');create.classList.remove('hidden');create.dataset.slot=slot;error.textContent=''}
document.getElementById('back').onclick=()=>{create.classList.add('hidden');cards.classList.remove('hidden');document.querySelector('.intro')?.classList.remove('hidden')};
document.getElementById('createBtn').onclick=async()=>{error.textContent='';const data={slot:Number(create.dataset.slot),firstname:v('firstname'),lastname:v('lastname'),nationality:v('nationality'),birthdate:v('birthdate'),gender:v('gender')};if(!data.firstname||!data.lastname||!data.nationality||!data.birthdate){error.textContent='Please complete every field.';return}const r=await nui('create',data);if(!r.ok)error.textContent=r.error||'Unable to create character.'};
function v(id){return document.getElementById(id).value.trim()}function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
window.addEventListener('message',e=>{const d=e.data||{};if(d.action==='open')app.classList.remove('hidden');if(d.action==='characters')render(d.characters);if(d.action==='transition'){app.classList.remove('hidden');const sub=document.querySelector('.sub');if(sub)sub.textContent=d.text||'Loading...'}if(d.action==='hide')app.classList.add('hidden')});
